import { sha256 } from "./hash.js";
import { stableStringify } from "./normalize.js";
import { createJavaEndpointAnalyzer } from "./javaEndpointAnalysis.js";
import { createEndpointReplacementPlanFromJava } from "./endpointReplacementPlanner.js";
import type { EndpointWorkloadKind } from "./endpointReplacementModel.js";

export interface RepositoryRustAssessmentOptions { root: string; maxDepth?: number; maxEdges?: number; limit?: number; includeTests?: boolean; adaptive?: boolean; maxExpansionDepth?: number; maxExpansionEdges?: number; maxExpansionRounds?: number; }
export interface RepositoryMethodAssessment { id: string; file: string; line: number; repository: string; method: string; signature: string; role: "repository" | "mapper" | "dao"; implementation: "concrete" | "default" | "generated-boundary"; workload: EndpointWorkloadKind; operation: "read" | "write" | "delete" | "ddl" | "dynamic-sql" | "unknown"; status: "ready" | "blocked"; nodes: number; edges: number; externalBoundaries: number; unknownNodes: number; findings: string[]; expansionStatus?: "complete" | "budget-exhausted"; expansionRounds?: number; }
export interface RepositoryRustAssessmentReport { version: 1; createdAt: string; root: string; repositoryMethodCount: number; assessedCount: number; summary: { ready: number; blocked: number; generatedBoundaries: number; withUnknownNodes: number; adaptivelyExpanded: number; expansionBudgetExhausted: number; roles: Record<string, number>; operations: Record<string, number>; findings: Record<string, number> }; methods: RepositoryMethodAssessment[]; reportHash: string; }

export async function assessJavaRepositoriesForRust(options: RepositoryRustAssessmentOptions): Promise<RepositoryRustAssessmentReport> {
  const analyzer = await createJavaEndpointAnalyzer(options.root, Boolean(options.includeTests));
  const candidates = analyzer.repositoryMethods.slice(0, positiveLimit(options.limit, analyzer.repositoryMethods.length));
  const methods = candidates.map((candidate): RepositoryMethodAssessment => {
    const expansion = options.adaptive ? analyzer.analyzeRepositoryMethodAdaptive(candidate, { initialDepth: options.maxDepth, initialEdges: options.maxEdges, maxDepth: options.maxExpansionDepth, maxEdges: options.maxExpansionEdges, maxRounds: options.maxExpansionRounds }) : undefined;
    const source = expansion?.report ?? analyzer.analyzeRepositoryMethod(candidate, { maxDepth: options.maxDepth, maxEdges: options.maxEdges });
    const { graph, plan } = createEndpointReplacementPlanFromJava(source);
    const findings = [...plan.findings];
    if (candidate.implementation === "generated-boundary") findings.push("RP-REPOSITORY-GENERATED-IMPLEMENTATION");
    if (expansion?.status === "budget-exhausted") findings.push("RP-GRAPH-EXPANSION-BUDGET-EXHAUSTED");
    return { id: candidate.id, file: candidate.file, line: candidate.line, repository: candidate.qualifiedClassName, method: candidate.methodName, signature: candidate.signature, role: candidate.role, implementation: candidate.implementation, workload: graph.workload, operation: classifyOperation(candidate.methodName, candidate.signature), status: candidate.implementation === "generated-boundary" ? "blocked" : plan.status, nodes: graph.nodes.length, edges: graph.edges.length, externalBoundaries: graph.nodes.filter((node) => node.id.startsWith("external:")).length, unknownNodes: graph.nodes.filter((node) => node.kind === "unknown").length, findings: [...new Set(findings)].sort(), expansionStatus: expansion?.status, expansionRounds: expansion?.rounds.length };
  });
  const base = { version: 1 as const, createdAt: new Date().toISOString(), root: analyzer.root, repositoryMethodCount: analyzer.repositoryMethods.length, assessedCount: methods.length, summary: { ready: methods.filter((x) => x.status === "ready").length, blocked: methods.filter((x) => x.status === "blocked").length, generatedBoundaries: methods.filter((x) => x.implementation === "generated-boundary").length, withUnknownNodes: methods.filter((x) => x.unknownNodes > 0).length, adaptivelyExpanded: methods.filter((x) => (x.expansionRounds ?? 0) > 1).length, expansionBudgetExhausted: methods.filter((x) => x.expansionStatus === "budget-exhausted").length, roles: count(methods.map((x) => x.role)), operations: count(methods.map((x) => x.operation)), findings: count(methods.flatMap((x) => x.findings)) }, methods };
  return { ...base, reportHash: sha256(stableStringify({ ...base, createdAt: undefined })) };
}
export function renderRepositoryRustAssessment(report: RepositoryRustAssessmentReport): string { return ["# Repository Rust Assessment", "", `- Root: ${report.root}`, `- Repository methods: ${report.repositoryMethodCount}`, `- Assessed: ${report.assessedCount}`, `- Ready: ${report.summary.ready}`, `- Blocked: ${report.summary.blocked}`, `- Generated boundaries: ${report.summary.generatedBoundaries}`, `- Report hash: ${report.reportHash}`, "", "## Findings", "", ...Object.entries(report.summary.findings).sort((a,b) => b[1]-a[1] || a[0].localeCompare(b[0])).map(([k,v]) => `- ${k}: ${v}`), ""].join("\n"); }
function classifyOperation(name: string, signature: string): RepositoryMethodAssessment["operation"] { const text = `${name} ${signature}`; if (/dynamic|sql/i.test(name) || /@(SelectProvider|InsertProvider|UpdateProvider|DeleteProvider)\b/.test(signature)) return "dynamic-sql"; if (/createTable|alterTable|dropTable|truncate/i.test(text)) return "ddl"; if (/delete|remove|purge/i.test(text)) return "delete"; if (/save|insert|update|upsert|batch|command/i.test(text)) return "write"; if (/find|get|query|select|list|page|count|exists|load/i.test(text)) return "read"; return "unknown"; }
function count(values: string[]): Record<string, number> { const result: Record<string, number> = {}; for (const value of values) result[value] = (result[value] ?? 0) + 1; return Object.fromEntries(Object.entries(result).sort(([a],[b]) => a.localeCompare(b))); }
function positiveLimit(value: number | undefined, fallback: number): number { return Number.isInteger(value) && (value as number) > 0 ? value as number : fallback; }
